/* O bloco try catch vai tentar executar um código, caso não consiga ele retorna o 
erro que esse codigo gerou*/
// Muito utilizado!!


//b = 2

try{
    let a = 2 + b;
}catch(Error){
    console.log(Error)
}
console.log('teste')
